### PR TITLE
Minor fix to location of metadata box

### PR DESCRIPTION
**Pull request by drbrownman**
This fix seems to work more reliably with iPhone HEIC files. May not be perfect still.
FYI @jim-liu

### CODE REVIEW

**Comment by jim-liu** [comment]
@drbrownman The 3971 number was based on the HEIC file structure from https://cheeky4n6monkey.blogspot.com/2017/10/monkey-takes-heic.html. I have seen a few files taken by an iPhone Xs that have a different EXIF offset, but this fix doesn't seem to parse them correctly either. Do you have a sample that works with this fix but not the original?

**Comment by drbrownman** [comment]
Good to know @jim-liu 
I tested it off files from iPhone 7. Here is a sample [file](https://doc-14-1o-docs.googleusercontent.com/docs/securesc/17jr7jn054mgl4lkbnpplv91k9gogntg/ckbc0vio5mgbkhnlaiqdnrje5744b6to/1566396000000/07562857250612923405/07562857250612923405/1vbl8osA383ZVssmNFOfb1Zh0_7gehXe6?e=download&nonce=rknp3pq8mct3s&user=07562857250612923405&hash=f9dtciiqv1g7fkeru07m44hghevil2og).

If you can, send a iphoneX heic file sample.

**Comment by drbrownman** [comment]
Tested with some iPhone 8 files I could get my hands on. Looks like some of those files had a EXIF metadata as well as a XMP metadata section. New fix seems to work for those files.

**Comment by jim-liu** [comment]
Thanks for the new fix. I will test it with the files I have tomorrow. In the mean time, [these](https://send.firefox.com/download/2df6c5187c652638/#cimSk_Irs2ecuQ0Z32zDwQ) were taken with an iPhone Xs and have issues with the original and your first fix.

**Comment by drbrownman** [comment]
Try with the most recent fix. Seems to pass for all the HEIC files i am testing with at the moment.

**Comment by jim-liu** [comment]
Thanks! I tested a few different HEIC files (iPhone 6s, SE, 8 and Xs) and they all worked! Also tested the findEXIFinJPEG method against some JPEG files taken by iPhones and Windows Phones and all worked as well.

I cleaned up the code a bit. If it looks good to you I will merge the PR.

**Comment by drbrownman** [comment]
All good. Go for it.

**Pull request merged**
